### ISSUE TITLE
when run the make_data_files,always show the error" has type str, but expected one of: bytes"

### ISSUE THREAD

**Issue by angeluau** [rohithreddy024/Text-Summarizer-Pytorch#1]

**Comment by rohithreddy024** [comment]
As I mentioned in the instructions, you need to run make_data_files.py with Python 2. Hope this works..

**Comment by angeluau** [comment]
i use the python2.7,tensorflow1.8.0, still show the problem, thank your for your reply

**Comment by rohithreddy024** [comment]
I just now executed make_data_files.py using python 2.7, tensorflow 1.8.0 and it's running fine. Please recheck which python version you are using. I suggest you to create new python 2 environment using conda and install tensorflow in it using pip.

**Comment by angeluau** [comment]
i checked the enviroment,and i try to config the python27 enviroment, but conflicts with current version,can  Will you package the processed data and send it to my mailbox?I really need your help.------------------taeyanglucky@qq.com

**Comment by rohithreddy024** [comment]
Done!!
