### ISSUE TITLE
intra decoder code doesn't match paper

### ISSUE THREAD

**Issue by bhomass** [rohithreddy024/Text-Summarizer-Pytorch#10]
The intra decoder code in model.py (lines 124 to 133) does not match either paper. The referenced pointer-generator paper, eqn 1, uses encoder hidden states, current decoder state, and a bias term. There is no mention of list of previous decoder states. In the other paper, "deep reinforced model...", there is use of prev decoder states, but not in the way you have it in the code. Can you point to the specific formula that's behind your code?

**Comment by rohithreddy024** [comment]
The goal of Intra-Decoder attention is that, given previous decoder hidden states (h0,...,ht-1) and current decoder hidden state (ht), we need to generate scores (e0,....et-1) over previous decoder hidden states w.r.t the current one. Now, there are lot of attention functions that can be used for the implementation of intra-decoder attention such as additive, bilinear, dot product etc. "Deep Reinforced Model" paper used bilinear function for all its attention mechanisms whereas "Pointer-Generator Network" paper used additive function for all its attention mechanisms. I initially tried using bilinear function but it was giving numerical overflow problems and thus I had to use additive function. For more info about attention functions check under "Family of attention mechanisms" section in [this article](https://lilianweng.github.io/lil-log/2018/06/24/attention-attention.html)

**Comment by alphanlp** [comment]
do you encounter  error like this?  when Id change the attention mechanisms as paper given, i get error as follows after running successfully a while

19/06/13 19:59:01 INFO CommandUtil: /pytorch/aten/src/THC/THCTensorRandom.cuh:188: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [121,0,0], thread: [920,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.

**Comment by rohithreddy024** [comment]
Yeah.. When you change the attention mechanism to the one given in the paper, you might encounter numerical overflow problem. Because of this, the probability distribution vector over vocab contain `nan` values and when you try to sample from this distribution, you will encounter this kind of error.

**Comment by sayan3710** [comment]
How do we overcome this error??
