### ISSUE TITLE
No coverage for pointer generator?

### ISSUE THREAD

**Issue by Shashi456** [rohithreddy024/Text-Summarizer-Pytorch#11]
There seems to be no coverage loss implemented for the pointer generator, is there any way i could go about implementing it?

**Comment by rohithreddy024** [comment]
You can refer this [pytorch implementation of pointer generator network](https://github.com/atulkum/pointer_summarizer). My implementation is more of [this paper](https://arxiv.org/pdf/1705.04304.pdf)
