### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by Shashi456** [rohithreddy024/Text-Summarizer-Pytorch#13]
So I'm trying to train this model on my GPU, and it takes about 1800 seconds for 1000 steps so about 10 days training time. Could you tell me if you had a similar experience if not, how long did it take you to train the model?

**Comment by rohithreddy024** [comment]
I trained on GTX 1080 Ti, and if I remember correctly, it took me around 5 days for the whole training process.  Check out my [training log](https://github.com/rohithreddy024/Text-Summarizer-Pytorch/blob/master/training_log.txt) to know optimal range of time steps at which model is giving best results and train accordingly. You can further reduce training time.
