### ISSUE TITLE
the problem of  x_t

### ISSUE THREAD

**Issue by 980202006** [rohithreddy024/Text-Summarizer-Pytorch#19]
I can not understand the code in the 76 line of train.py 
why use start_id to fill the x_t ?
x_t = get_cuda(T.LongTensor(len(enc_out)).fill_(self.start_id))

**Comment by rohithreddy024** [comment]
Many text generation models are of the form: product P(w1|<start_id>)P(w2|w1)....P(wn|wn-1). Here the probability distribution over w1 (first word of the sequence) is conditioned on <start_id> and encoder hidden states.
