### ISSUE TITLE
how to pre-process CNN/DM？

### ISSUE THREAD

**Issue by Stephen-Adams** [rohithreddy024/Text-Summarizer-Pytorch#2]
could you please tell me how to use your framework with CNN/DM dataset？
I don't know how to create .bin files with CNN/DM? 
Please inspire me with something, tutorial or else.

**Comment by Stephen-Adams** [comment]
I have found this  :  https://github.com/abisee/cnn-dailymail
Is that what I should do ？

**Comment by rohithreddy024** [comment]
Yeah.. Also, cnn-dailymail abstracts are created by merging multiple sentences (multiple python strings) which is not the case of gigaword abstracts (single python string). So you need to take care of this difference while using my batcher.py file. I suggest you to take a look at [this](https://github.com/atulkum/pointer_summarizer) where they create .bin files for cnn-dailymail in pytorch

**Comment by Stephen-Adams** [comment]
thank you very much～

**Comment by xcfcode** [comment]
@Stephen-Adams Could you please share your modifications?

**Comment by kscp123** [comment]
@rohithreddy024 can you explain why use bin file but not txt file? Thanks.

**Comment by rohithreddy024** [comment]
@kscp123 I am using the same batcher.py file as that of [this](https://github.com/abisee/pointer-generator) and [this](https://github.com/atulkum/pointer_summarizer). So I am following their bin format convention. As for as the use cases of binary formatted input, you can just google them.
