### ISSUE TITLE
python2 not support tensorflow

### ISSUE THREAD

**Issue by hellomaxwell** [rohithreddy024/Text-Summarizer-Pytorch#22]
first step python make_data_files.py 
but make_data_files.py need import tensorflow, code like:
from tensorflow.core.example import example_pb2
how to solve this problem?

**Comment by kkwellbbetter** [comment]
I have the same questions,could you have solve it?

**Comment by rohithreddy024** [comment]
[pull request 20](https://github.com/rohithreddy024/Text-Summarizer-Pytorch/pull/20)
Check if this can help. Although I didn't check whether it works or not, you can try it.
