### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by srijangoyal** [rohithreddy024/Text-Summarizer-Pytorch#4]
Hi, could you provide the best trained model?

**Comment by rohithreddy024** [comment]
You can download from google drive using this [link](https://drive.google.com/file/d/1AOWv9ZDXPAa5DGftRQ4ORDrHALKdX2DL/view?usp=sharing)

**Comment by BorisTitarenko** [comment]
Could you provide that model again please?

**Comment by renata-kreso** [comment]
> You can download from google drive using this [link](https://drive.google.com/file/d/1AOWv9ZDXPAa5DGftRQ4ORDrHALKdX2DL/view?usp=sharing)

The link is no longer working, could you please reupload it?

**Comment by GISScience** [comment]
Sorry, the file you have requested does not exist.

Make sure that you have the correct URL and the file exists.

The link is no longer working, could you please reupload it?
