### ISSUE TITLE
Hello, is the "0050000.tar" in the second command generated by the program?

### ISSUE THREAD

**Issue by SStarLib** [rohithreddy024/Text-Summarizer-Pytorch#5]

**Comment by rohithreddy024** [comment]
In second command, it's `0005000.tar` and not `0050000.tar`. Yes, it is generated by the program and is the first saved model.

**Comment by SStarLib** [comment]
> In second command, it's `0005000.tar` and not `0050000.tar`. Yes, it is generated by the program and is the first saved model.
Sorry, I wrote the wrong file name. I created an empty file called 0005000.tar and the program will get an error，so, when you first started eval.py, how did the 000500.tar file come from?

**Comment by rohithreddy024** [comment]
You need to run the first command under [Training Section](https://github.com/rohithreddy024/Text-Summarizer-Pytorch#training) i.e: `python train.py --train_mle=yes --train_rl=no --mle_weight=1.0`.   train.py generate the saved models.
