### ISSUE TITLE
Beam Search get_current_state deletes OOV tokens

### ISSUE THREAD

**Issue by palle-k** [rohithreddy024/Text-Summarizer-Pytorch#8]
In [Beam.get_current_state() in beam_search.py](https://github.com/rohithreddy024/Text-Summarizer-Pytorch/blob/master/beam_search.py#L24), setting OOV tokens to UNK also changes `self.tokens`, as `self.tokens[:, -1]` returns a view to the same underlying memory.

This leads to a bug, where `beam_search` never decodes OOV words.

Fix: Use `.clone()`, to create a copy of the tensor.

```python
tokens = self.tokens[:, -1].clone()
```

**Comment by rohithreddy024** [comment]
Thanks for pointing it out. Fixed it :)
